#!/usr/bin/env php
<?php
// application.php

require_once __DIR__ . '/bootstrap.php';
require_once __DIR__ . '/../builder/GreetCommand.php';

use Console\Command\GreetCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new GreetCommand);
$application->run();