#!/usr/bin/env php
<?php
// application.php

require_once __DIR__ . '/../builder/bootstrap.php';

require_once __DIR__ . '/../builder/BundleCommand.php';

use Symfony\Component\Console\Application;

use Builder\BundleCommand;

$application = new Application();

$application->add(new BundleCommand);

$application->run();