#!/usr/bin/env php
<?php
// application.php

require_once __DIR__ . '/bootstrap.php';

require_once __DIR__ . '/../Builder/BundleCommand.php';

use Symfony\Component\Console\Application;



use Builder\BundleCommand;


$application = new Application();


$application->add(new BundleCommand);

$application->run();