#!/usr/bin/env php

<?php

require_once __DIR__.'/../vendor/autoload.php';
require_once 'Bob/ControllerBuilder.php';
require_once 'Bob/ControllerCoreBuilder.php';
require_once 'Bob/RepositoryCoreBuilder.php';

use Symfony\Component\ClassLoader\UniversalClassLoader;
use TwigGenerator\Builder\Generator;
use \Bob\ControllerBuilder;
use \Bob\ControllerCoreBuilder;
use \Bob\RepositoryCoreBuilder;

$loader = new UniversalClassLoader();

$command = $argv[1];
$rawArguments = $argv;
$throwAway = array_shift($rawArguments);
$throwAway = array_shift($rawArguments);
$entityList = $rawArguments;
print_r($entityList);

$config = array(
    'phpVersion' => "5.3.18",
    'category' => 'Api_Rest_Implementation',
    'organisation' => 'Thinkadoo',
    'author' => 'Andre Venter',
    'authorEmail' => 'andre.n.venter@gmail.com',
    'corganisationWebSite' => 'http://think-a-doo.net',
    'repository' => 'https://github.com/thinkadoo/silex-skeleton-rest.git'
    );

switch ($command) {

    case "bundle":
        makeControllers($entityList, $config);
        makeCoreControllers($entityList, $config);
        makeCoreRepositories($entityList, $config);
        break;

    case "core":
        makeCoreControllers($entityList, $config);
        makeCoreRepositories($entityList, $config);
        break;

    case "controller":
        makeControllers($entityList, $config);
        makeCoreControllers($entityList, $config);
        break;

    case "repository":
        makeCoreRepositories($entityList, $config);
        break;

    case "corecontroller":
        makeCoreControllers($entityList, $config);
        break;

    case "corerepository":
        makeCoreRepositories($entityList, $config);
        break;

}

    function makeCoreControllers($entityList, $config)
    {

        $phpVersion = $config['phpVersion'];
        $category = $config['category'];
        $organisation = $config['organisation'];
        $author = $config['author'];
        $authorEmail = $config['authorEmail'];
        $corganisationWebSite = $config['corganisationWebSite'];
        $repository = $config['repository'];

        // ControllerCore

        foreach($entityList as $className)
        {
            $nameSpace = $className. '\\' . $className . 'Bundle\\Core';
            $moduleName = $className;

            $bobCoreController = new ControllerCoreBuilder();
            $bobCoreController->setOutputName('ControllerCore.php');

            $bobCoreController->setVariable('phpVersion', $phpVersion);
            $bobCoreController->setVariable('category', $category);
            $bobCoreController->setVariable('author', $author);
            $bobCoreController->setVariable('organisation', $organisation);
            $bobCoreController->setVariable('organisationWebSite', $corganisationWebSite);
            $bobCoreController->setVariable('repository', $repository);

            $bobCoreController->setVariable('className', $className);
            $bobCoreController->setVariable('implements', 'ControllerProviderInterface');
            $bobCoreController->setVariable('moduleName', $moduleName);
            $bobCoreController->setVariable('author', $author);
            $bobCoreController->setVariable('authorEmail', $authorEmail);

            $generateCoreController = new Generator();
            $generateCoreController->setTemplateDirs(array(__DIR__.'/Bob/Work/ControllerCoreTemplate/',));
            $generateCoreController->setMustOverwriteIfExists(true);
            $generateCoreController->setVariables(array('namespace' => $nameSpace,));

            $generateCoreController->addBuilder($bobCoreController);

            $generateCoreController->writeOnDisk(__DIR__.'/../src/'.$className.'/'.$className.'Bundle/Core');
            print_r('Done Generating Controller Core '.$className.' ;) ');

        }
    }

    function makeControllers($entityList, $config){

        $phpVersion = $config['phpVersion'];
        $category = $config['category'];
        $organisation = $config['organisation'];
        $author = $config['author'];
        $authorEmail = $config['authorEmail'];
        $corganisationWebSite = $config['corganisationWebSite'];
        $repository = $config['repository'];

        // Controller

        foreach($entityList as $className){

            $nameSpace = $className. '\\' . $className . 'Bundle\\Controller';
            $moduleName = $className;

            $bobController = new ControllerBuilder();
            $bobController->setOutputName($className.'Controller.php');

            $bobController->setVariable('phpVersion', $phpVersion);
            $bobController->setVariable('category', $category);
            $bobController->setVariable('author', $author);
            $bobController->setVariable('organisation', $organisation);
            $bobController->setVariable('organisationWebSite', $corganisationWebSite);
            $bobController->setVariable('repository', $repository);

            $bobController->setVariable('className', $className);
            $bobController->setVariable('extends', 'ControllerCore');
            $bobController->setVariable('moduleName', $moduleName);
            $bobController->setVariable('author', $author);
            $bobController->setVariable('authorEmail', $authorEmail);

            $generateController = new Generator();
            $generateController->setTemplateDirs(array(__DIR__.'/Bob/Work/ControllerTemplate/',));
            $generateController->setMustOverwriteIfExists(true);
            $generateController->setVariables(array('namespace' => $nameSpace,));

            $generateController->addBuilder($bobController);

            $generateController->writeOnDisk(__DIR__.'/../src/'.$className.'/'.$className.'Bundle/Controller');
            print_r('Done Generating Controller '.$className.' ;) ');

        }
    }

    function makeCoreRepositories($entityList, $config)
    {
        $phpVersion = $config['phpVersion'];
        $category = $config['category'];
        $organisation = $config['organisation'];
        $author = $config['author'];
        $authorEmail = $config['authorEmail'];
        $corganisationWebSite = $config['corganisationWebSite'];
        $repository = $config['repository'];

        // RepositoryCore

        foreach($entityList as $className){

            $nameSpace = $className. '\\' . $className . 'Bundle\\Core';
            $moduleName = $className;

            $bobCoreRepository = new RepositoryCoreBuilder();
            $bobCoreRepository->setOutputName('RepositoryCore.php');

            $bobCoreRepository->setVariable('phpVersion', $phpVersion);
            $bobCoreRepository->setVariable('category', $category);
            $bobCoreRepository->setVariable('author', $author);
            $bobCoreRepository->setVariable('organisation', $organisation);
            $bobCoreRepository->setVariable('organisationWebSite', $corganisationWebSite);
            $bobCoreRepository->setVariable('repository', $repository);

            $bobCoreRepository->setVariable('className', $className);
            $bobCoreRepository->setVariable('moduleName', $moduleName);
            $bobCoreRepository->setVariable('author', $author);
            $bobCoreRepository->setVariable('authorEmail', $authorEmail);

            $generateCoreRepository = new Generator();
            $generateCoreRepository->setTemplateDirs(array(__DIR__.'/Bob/Work/RepositoryCoreTemplate/',));
            $generateCoreRepository->setMustOverwriteIfExists(true);
            $generateCoreRepository->setVariables(array('namespace' => $nameSpace,));

            $generateCoreRepository->addBuilder($bobCoreRepository);

            $generateCoreRepository->writeOnDisk(__DIR__.'/../src/'.$className.'/'.$className.'Bundle/Core');
            print_r('Done Generating Repository Core '.$className.' ;) ');

        }
    }
